from __future__ import annotations

from juno_v2.contracts.modes import ModePolicy

# Built-in mode ids (spec 1.2). technical_precise is intentionally excluded.
BUILTIN_MODE_NAMES: tuple[str, ...] = (
    "default_surface",
    "verbatim",
    "casual_chat",
    "formal_email",
    "structured_notes",
    "explicit_rewrite",
    "command_mode",
)


def builtin_mode_names() -> list[str]:
    return list(BUILTIN_MODE_NAMES)


def _p(
    mode_name: str,
    *,
    base_mode: str,
    manual_selectable: bool,
    writer_behavior: str,
    transform_behavior: str,
    command_behavior: str,
    itn_policy: str,
    punctuation_policy: str,
    cleanup_policy: str,
    snippet_scope_policy: str,
    style_scope_policy: str,
    allow_auto_transform: bool,
    allow_model_insert_rewrite: bool,
    allow_inline_commands: bool,
    allow_recent_target_commands: bool,
    allow_selection_commands: bool,
    command_ambiguity_policy: str,
    degradation_behavior: str,
    prompt_prefix: str,
    post_processors: tuple[str, ...] = (),
    transcript_correction_policy: str = "standard",
    live_correction_policy: str = "stable_span_standard",
    final_formatting_policy: str = "minimal",
) -> ModePolicy:
    return ModePolicy(
        mode_name=mode_name,
        base_mode=base_mode,
        manual_selectable=manual_selectable,
        writer_behavior=writer_behavior,
        transform_behavior=transform_behavior,
        command_behavior=command_behavior,
        itn_policy=itn_policy,
        punctuation_policy=punctuation_policy,
        cleanup_policy=cleanup_policy,
        snippet_scope_policy=snippet_scope_policy,
        style_scope_policy=style_scope_policy,
        allow_auto_transform=allow_auto_transform,
        allow_model_insert_rewrite=allow_model_insert_rewrite,
        allow_inline_commands=allow_inline_commands,
        allow_recent_target_commands=allow_recent_target_commands,
        allow_selection_commands=allow_selection_commands,
        command_ambiguity_policy=command_ambiguity_policy,
        degradation_behavior=degradation_behavior,
        prompt_prefix=prompt_prefix,
        post_processors=post_processors,
        transcript_correction_policy=transcript_correction_policy,
        live_correction_policy=live_correction_policy,
        final_formatting_policy=final_formatting_policy,
    )


# Policies follow spec 1.6 (behavioral tags are inspectable; writer applies subsets).
BUILTIN_MODES: dict[str, ModePolicy] = {
    "default_surface": _p(
        "default_surface",
        base_mode="default_surface",
        manual_selectable=False,
        writer_behavior="surface_aware_light_cleanup",
        transform_behavior="standard",
        command_behavior="inline_moderate_ambiguity",
        itn_policy="surface_default",
        punctuation_policy="standard",
        cleanup_policy="light_only",
        snippet_scope_policy="surface_plus_global",
        style_scope_policy="surface_plus_global",
        allow_auto_transform=True,
        allow_model_insert_rewrite=False,
        allow_inline_commands=True,
        allow_recent_target_commands=True,
        allow_selection_commands=True,
        command_ambiguity_policy="moderate_threshold",
        degradation_behavior="graceful",
        prompt_prefix="",
        transcript_correction_policy="standard",
        live_correction_policy="stable_span_standard",
        final_formatting_policy="minimal",
    ),
    "verbatim": _p(
        "verbatim",
        base_mode="verbatim",
        manual_selectable=True,
        writer_behavior="passthrough_no_semantic",
        transform_behavior="minimal",
        command_behavior="strict_narrow",
        itn_policy="literal_minimal",
        punctuation_policy="literal_minimal",
        cleanup_policy="minimal_only",
        snippet_scope_policy="none_unless_invoked",
        style_scope_policy="none",
        allow_auto_transform=False,
        allow_model_insert_rewrite=False,
        allow_inline_commands=True,
        allow_recent_target_commands=True,
        allow_selection_commands=True,
        command_ambiguity_policy="strict_threshold",
        degradation_behavior="prefer_raw",
        prompt_prefix="Verbatim dictation: preserve spoken text; no stylistic shaping.",
        transcript_correction_policy="none",
        live_correction_policy="none",
        final_formatting_policy="none",
    ),
    "casual_chat": _p(
        "casual_chat",
        base_mode="casual_chat",
        manual_selectable=True,
        writer_behavior="messaging_cleanup_light_filler",
        transform_behavior="light",
        command_behavior="inline_allowed",
        itn_policy="messaging",
        punctuation_policy="light",
        cleanup_policy="messaging_oriented",
        snippet_scope_policy="messaging_plus_global",
        style_scope_policy="prefer_messaging",
        allow_auto_transform=True,
        allow_model_insert_rewrite=False,
        allow_inline_commands=True,
        allow_recent_target_commands=True,
        allow_selection_commands=True,
        command_ambiguity_policy="moderate_threshold",
        degradation_behavior="graceful",
        prompt_prefix="Casual messaging tone: short clauses; avoid formal overreach.",
        transcript_correction_policy="standard",
        live_correction_policy="stable_span_standard",
        final_formatting_policy="messaging",
    ),
    "formal_email": _p(
        "formal_email",
        base_mode="formal_email",
        manual_selectable=True,
        writer_behavior="strong_cleanup_paragraph_shaping",
        transform_behavior="model_polish_allowed",
        command_behavior="narrower_than_casual",
        itn_policy="standard",
        punctuation_policy="strong",
        cleanup_policy="grammar_and_paragraphs",
        snippet_scope_policy="email_plus_global",
        style_scope_policy="prefer_email",
        allow_auto_transform=True,
        allow_model_insert_rewrite=True,
        allow_inline_commands=True,
        allow_recent_target_commands=True,
        allow_selection_commands=True,
        command_ambiguity_policy="narrow_threshold",
        degradation_behavior="graceful",
        prompt_prefix="Formal email: complete sentences; polite professional tone.",
        transcript_correction_policy="standard",
        live_correction_policy="stable_span_standard",
        final_formatting_policy="email",
    ),
    "structured_notes": _p(
        "structured_notes",
        base_mode="structured_notes",
        manual_selectable=True,
        writer_behavior="structural_lists_headings",
        transform_behavior="structural_allowed",
        command_behavior="standard",
        itn_policy="standard",
        punctuation_policy="standard",
        cleanup_policy="structure_forward",
        snippet_scope_policy="docs_plus_global",
        style_scope_policy="prefer_docs",
        allow_auto_transform=True,
        allow_model_insert_rewrite=False,
        allow_inline_commands=True,
        allow_recent_target_commands=True,
        allow_selection_commands=True,
        command_ambiguity_policy="moderate_threshold",
        degradation_behavior="graceful",
        prompt_prefix="Structured notes: bullets, numbering, headings when spoken.",
        transcript_correction_policy="standard",
        live_correction_policy="stable_span_standard",
        final_formatting_policy="structured_notes",
    ),
    "explicit_rewrite": _p(
        "explicit_rewrite",
        base_mode="explicit_rewrite",
        manual_selectable=True,
        writer_behavior="model_assisted",
        transform_behavior="wide_safe_defaults",
        command_behavior="full_target_resolution",
        itn_policy="standard",
        punctuation_policy="standard",
        cleanup_policy="full",
        snippet_scope_policy="all_scopes",
        style_scope_policy="all_styles",
        allow_auto_transform=True,
        allow_model_insert_rewrite=True,
        allow_inline_commands=True,
        allow_recent_target_commands=True,
        allow_selection_commands=True,
        command_ambiguity_policy="low_threshold",
        degradation_behavior="explain",
        prompt_prefix="Explicit rewrite mode: user expects AI shaping.",
        transcript_correction_policy="standard",
        live_correction_policy="stable_span_standard",
        final_formatting_policy="explicit_rewrite",
    ),
    "command_mode": _p(
        "command_mode",
        base_mode="command_mode",
        manual_selectable=True,
        writer_behavior="command_only_dictation_narrow",
        transform_behavior="command_or_edit_only",
        command_behavior="wide_parser_narrow_dictation_fallback",
        itn_policy="standard",
        punctuation_policy="standard",
        cleanup_policy="minimal_for_commands",
        snippet_scope_policy="none",
        style_scope_policy="none",
        allow_auto_transform=False,
        allow_model_insert_rewrite=True,
        allow_inline_commands=True,
        allow_recent_target_commands=True,
        allow_selection_commands=True,
        command_ambiguity_policy="confidence_gated",
        degradation_behavior="emit_ambiguity_metadata",
        prompt_prefix="Command mode: interpret as edit/transform commands; narrow free dictation.",
        post_processors=("command_ambiguity_check",),
        transcript_correction_policy="exact_only",
        live_correction_policy="none",
        final_formatting_policy="command_generate",
    ),
}
